'use client';
import { FormEvent, useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Check, ChevronLeft, Copy, Crown, Link2, MessageCircle, MoreHorizontal, Send, Settings, Share2, Signal, Users, Wifi, WifiOff } from 'lucide-react';
import { io, Socket } from 'socket.io-client';
import { Brand } from './brand';
import { ThemeSwitcher } from './theme-switcher';
import { api, ensureGuest, getSession, socketUrl } from '@/lib/api';
import { PlayerAdapter, YouTubePlayerAdapter } from '@/lib/player-adapter';

interface Participant { userId: string; role: 'owner' | 'moderator' | 'viewer'; online: boolean; latencyMs: number | null; user: { displayName: string }; }
interface Message { id: string; userId: string; displayName: string; body: string; sentAt: string; }
interface Playback { videoId: string; state: 'playing' | 'paused' | 'buffering' | 'ended'; positionMs: number; sequence: number; controllerUserId: string | null; }
interface Snapshot { room: { id: string; name: string; inviteCode: string; ownerId: string }; playback: Playback; participants: Participant[]; messages: Message[]; }
export function RoomClient({ roomId }: { roomId: string }) {
  const router = useRouter(); const playerElement = useRef<HTMLDivElement>(null); const player = useRef<PlayerAdapter | null>(null); const socket = useRef<Socket | null>(null); const applyingRemote = useRef(false);
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [tab, setTab] = useState<'chat' | 'people'>('chat'); const [message, setMessage] = useState(''); const [connected, setConnected] = useState(false); const [copied, setCopied] = useState(false); const [error, setError] = useState('');
  useEffect(() => { let disposed = false; void (async () => { try { const session = await ensureGuest(); const initial = await api<Snapshot>(`/rooms/${roomId}`); if (disposed) return; setSnapshot(initial); const client = io(`${socketUrl}/rooms`, { auth: { token: session.accessToken }, reconnection: true }); socket.current = client; client.on('connect', () => { setConnected(true); client.emit('room:join', { roomId, lastSequence: initial.playback.sequence }); }); client.on('disconnect', () => setConnected(false)); client.on('room:snapshot', (next: Snapshot) => setSnapshot(next)); client.on('presence:changed', (participants: Participant[]) => setSnapshot((prev) => prev ? { ...prev, participants } : prev)); client.on('chat:message', (next: Message) => setSnapshot((prev) => prev ? { ...prev, messages: [...prev.messages, next] } : prev)); client.on('playback:state', (next: Playback) => { setSnapshot((prev) => prev ? { ...prev, playback: next } : prev); const adapter = player.current; if (!adapter) return; applyingRemote.current = true; if (next.videoId !== prevVideo(adapter, next.videoId)) adapter.load(next.videoId, next.positionMs); else { adapter.seekTo(next.positionMs); next.state === 'playing' ? adapter.play() : adapter.pause(); } window.setTimeout(() => applyingRemote.current = false, 500); }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Комната недоступна'); } })(); return () => { disposed = true; socket.current?.disconnect(); player.current?.destroy(); }; }, [roomId]);
  useEffect(() => { if (!snapshot || !playerElement.current || player.current) return; const adapter = new YouTubePlayerAdapter(playerElement.current, snapshot.playback.videoId); player.current = adapter; return adapter.subscribe((event) => { if (applyingRemote.current || !socket.current?.connected) return; if (event.state === 'playing' || event.state === 'paused') socket.current.emit('playback:intent', { roomId, action: event.state === 'playing' ? 'play' : 'pause', positionMs: event.positionMs }); }); }, [snapshot, roomId]);
  function send(event: FormEvent) { event.preventDefault(); if (!message.trim()) return; socket.current?.emit('chat:send', { roomId, body: message }); setMessage(''); }
  async function copyInvite() { if (!snapshot) return; await navigator.clipboard.writeText(`${location.origin}/invite/${snapshot.room.inviteCode}`); setCopied(true); setTimeout(() => setCopied(false), 1800); }
  if (error) return <main className="center-state"><WifiOff size={38}/><h1>{error}</h1><button onClick={() => router.push('/')}>На главную</button></main>;
  if (!snapshot) return <main className="room-loading"><div className="skeleton player-skeleton"/><div className="skeleton side-skeleton"/></main>;
  const me = getSession()?.user; const controller = snapshot.participants.find((p) => p.userId === snapshot.playback.controllerUserId);
  return <main className="room-page"><header className="room-header"><button className="icon-button" onClick={() => router.push('/')} aria-label="Назад"><ChevronLeft/></button><Brand/><div className="room-title"><h1>{snapshot.room.name}</h1><span className={connected ? 'connection online' : 'connection'}><i/>{connected ? 'Подключено' : 'Подключение…'}</span></div><div className="room-actions"><button className="share-button" onClick={copyInvite}>{copied ? <Check/> : <Share2/>}<span>{copied ? 'Скопировано' : 'Пригласить'}</span></button><ThemeSwitcher/><button className="icon-button"><Settings/></button></div></header>
    <div className="room-grid"><section className="watch-column"><div className="player-shell"><div ref={playerElement} className="youtube-player"/><div className="player-glow" aria-hidden="true"/></div><div className="video-meta"><div><span className="youtube-label">YOUTUBE</span><h2>Совместный просмотр</h2><p>Официальный YouTube-плеер · управление синхронизируется для всех</p></div><div className="sync-pill"><Signal size={17}/><span><b>Синхронизировано</b><small>{controller?.user.displayName ?? 'Сервер'} управляет · seq {snapshot.playback.sequence}</small></span></div></div><div className="mobile-room-actions"><button onClick={copyInvite}><Link2/> Ссылка</button><button onClick={() => setTab('people')}><Users/> {snapshot.participants.length}</button><button onClick={() => setTab('chat')}><MessageCircle/> Чат</button><ThemeSwitcher/></div></section>
      <aside className="side-panel"><div className="panel-tabs"><button className={tab === 'chat' ? 'active' : ''} onClick={() => setTab('chat')}>Чат <span>{snapshot.messages.length}</span></button><button className={tab === 'people' ? 'active' : ''} onClick={() => setTab('people')}>Участники <span>{snapshot.participants.length}</span></button></div>
        {tab === 'chat' ? <><div className="messages" aria-live="polite">{snapshot.messages.length === 0 && <div className="empty-chat"><MessageCircle/><h3>Здесь пока тихо</h3><p>Поздоровайтесь — друзья увидят сообщение сразу.</p></div>}{snapshot.messages.map((item) => <div className={`message ${item.userId === me?.id ? 'mine' : ''}`} key={item.id}><Avatar name={item.displayName}/><div><div className="message-head"><b>{item.displayName}</b><time>{new Date(item.sentAt).toLocaleTimeString('ru', { hour: '2-digit', minute: '2-digit' })}</time></div><p>{item.body}</p></div></div>)}</div><form className="chat-form" onSubmit={send}><input value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Написать сообщение…" maxLength={1000}/><button aria-label="Отправить"><Send size={18}/></button></form></> : <div className="participants"><div className="participant-summary"><span><Wifi size={15}/> {snapshot.participants.filter((p) => p.online).length} онлайн</span><small>Комната до 20 участников</small></div>{snapshot.participants.map((person) => <article key={person.userId}><div className="avatar-wrap"><Avatar name={person.user.displayName}/><i className={person.online ? 'presence online' : 'presence'}/></div><div><b>{person.user.displayName}{person.userId === me?.id && ' (вы)'}</b><span>{person.role === 'owner' ? 'Организатор' : person.role === 'moderator' ? 'Модератор' : 'Зритель'}</span></div>{person.role === 'owner' ? <Crown className="crown" size={18}/> : <button className="icon-button small"><MoreHorizontal/></button>}</article>)}</div>}
      </aside></div></main>;
}
function Avatar({ name }: { name: string }) { const initials = name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase(); return <span className="avatar" style={{ '--hue': `${[...name].reduce((sum, char) => sum + char.charCodeAt(0), 0) % 360}` } as React.CSSProperties}>{initials}</span>; }
function prevVideo(_adapter: PlayerAdapter, fallback: string) { return fallback; }
